apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ns.yaml
  - repo.yaml
  - argocd-hr.yaml
  ## rollouts is currently disabled. For more info, refer the yaml file ##
  # - argocd-rollouts-hr.yaml
  ## events depend on argocd rollouts.
  # - argocd-events-hr.yaml
