apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: "1.x"
    helm:
      valuesObject:
        alloy:
          configMap:
            content: |
              // Kubernetes pod discovery
              discovery.kubernetes "pods" {
                role = "pod"
              }

              // Relabel pod metadata for log labels
              discovery.relabel "pod_logs" {
                targets = discovery.kubernetes.pods.targets

                rule {
                  source_labels = ["__meta_kubernetes_pod_phase"]
                  regex         = "Pending|Succeeded|Failed|Unknown"
                  action        = "drop"
                }
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  target_label  = "namespace"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_name"]
                  target_label  = "pod"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_container_name"]
                  target_label  = "container"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_node_name"]
                  target_label  = "node"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
                  target_label  = "app"
                }
              }

              // Collect pod logs via Kubernetes API
              loki.source.kubernetes "pod_logs" {
                targets    = discovery.relabel.pod_logs.output
                forward_to = [loki.write.default.receiver]
              }

              // Write logs to Loki
              loki.write "default" {
                endpoint {
                  url       = "http://loki.monitoring.svc:3100/loki/api/v1/push"
                  tenant_id = "homelab"
                }
              }

              // OTLP receiver for application traces
              otelcol.receiver.otlp "default" {
                grpc {
                  endpoint = "0.0.0.0:4317"
                }
                http {
                  endpoint = "0.0.0.0:4318"
                }
                output {
                  traces = [otelcol.exporter.otlp.tempo.input]
                }
              }

              // Forward traces to Tempo
              otelcol.exporter.otlp "tempo" {
                client {
                  endpoint = "tempo.monitoring.svc:4317"
                  tls {
                    insecure = true
                  }
                }
              }
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              memory: 384Mi
        controller:
          type: daemonset
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
