apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.x"
    helm:
      valuesObject:
        deploymentMode: SingleBinary
        loki:
          auth_enabled: true
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2026-01-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            type: s3
            s3:
              endpoint: seaweedfs.sharmamohit.com:8333
              region: us-east-1
              s3ForcePathStyle: true
              insecure: true
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
          limits_config:
            retention_period: 720h
          compactor:
            retention_enabled: true
        singleBinary:
          replicas: 1
          persistence:
            storageClass: ceph-block
            size: 10Gi
          extraEnv:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: seaweedfs-s3-secret
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: seaweedfs-s3-secret
                  key: aws-secret-access-key
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 1Gi
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        gateway:
          enabled: false
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        lokiCanary:
          enabled: false
        test:
          enabled: false
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
