apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: "1.x"
    helm:
      valuesObject:
        tempo:
          storage:
            trace:
              backend: s3
              s3:
                bucket: tempo-traces
                endpoint: seaweedfs.sharmamohit.com:8333
                insecure: true
                forcepathstyle: true
                region: us-east-1
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: "0.0.0.0:4317"
                http:
                  endpoint: "0.0.0.0:4318"
          compactor:
            compaction:
              block_retention: 168h
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
        persistence:
          enabled: true
          storageClassName: ceph-block
          size: 10Gi
        serviceMonitor:
          enabled: true
        extraEnv:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: seaweedfs-s3-secret
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: seaweedfs-s3-secret
                key: aws-secret-access-key
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
