---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.14.5"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb
      interval: 12h
  values:
    prometheus:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
