---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph
      version: "1.19.x"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 12h
  timeout: 10m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: -1 # keep trying to remediate
    crds: CreateReplace # Upgrade CRDs on package update
  releaseName: rook-ceph
  values:
    # PSP removed in Kubernetes 1.25+ and rook-ceph 1.10+
    monitoring:
      enabled: false
