apiVersion: v1
kind: Secret
metadata:
    name: r53-credentials-secret
    namespace: cert-manager
type: Opaque
data:
    secret-access-key: ENC[AES256_GCM,data:xYg+7JVZY7VGPQX+hTevtdXYzgIa574mCUcTgOF4arfNA2IzWG4eOw==,iv:HxYQ5jbLKZhaS4yneyl3nEBD5jnrzqXeClkfP0dftv4=,tag:dxIlUigtv+TD1hN9STI4EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubmVJSEdNME9NMGdtVXRq
            RFJiSEk5OUNBWVY4WFc5WnVSNHAxWmdaZjN3Cis5QXBleG1jUU5VQXFLSkVCRkpi
            Kytsa0J0eUhYV1NMZkhhZjdHUFp3ek0KLS0tIDhLbDg0dUFqaWVpKzU3L01HYmVP
            ZXlnMjJCazlzS1F2bkdpL04ycCt1U0EKZrTt9uPtKZaPaVWXNLUyaiIK9pNHYBXE
            DY4V2QgdD0puvED15nW58GNlHibDjG/4Br83++0Am9JI5NNTTB3Uiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T07:44:06Z"
    mac: ENC[AES256_GCM,data:Aik4WrV2ogFpzAKN+TJyO4KwJFUeAzeoBUAHJ5e3JY1iCKxy/UJXoN8rSKxvCV/x1f/PkqtXnoMQollC+erBMGbQ2VfnwqlBWS6SQ0MhWr/ne99EYnKHqU3cCZgvVeLu3QuGcNKY8Ywp5YC2AzaGAl0EICR9D7kKzl92ztZ7OGA=,iv:uDwa7ctZ2FA55YxG/qspkJku20nsg9U+yhMHFlm0ieE=,tag:HI1KfvWsO+iHRhllyAYIOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
