apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:HyqUFQ8=,iv:PIQBEDESn7TALo3LGlqCrQv5/i7D3qM46yNjvofGWAM=,tag:c7QWVIPAo/qOIBhOuQgwfQ==,type:str]
    admin-password: ENC[AES256_GCM,data:k8BiC6xV9jhLnj5UE6vrP7ETAPHZnT2TgrUb4flIhy0=,iv:2bhWo2MwiOwvGHvFuuZDwWTyb78LB1QqsPifjNXd6oQ=,tag:m+iVyDAG5OmU4EvFrIZMXA==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUFRSMThVNU5YZm50K2pO
            cEhYUXRSTEJWelQzQ2ExMnZtc2tvV21yQlRnCkw2S0JjcHFOcms1VU54OFpXM2wx
            VCs3R1VnSGNsd0hmcGhDanNVbUdERjgKLS0tIGRDR3NjRy9FenRKa1RsdVVybENz
            UU5YeUJVNWxxdzdJb004MTgvSWpOOFUKeNn+9AZLSx0Y+bJk/NLSazz8KPhH5uio
            AtqIPGe9s8tn89yrlBdH9UFWuqAvDB/DV40MlmHLGe+fBw4qFJBqWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T05:48:56Z"
    mac: ENC[AES256_GCM,data:Xs8FUorhrANPAAD62H24MT+lwC6HtniVN37+0Is5Ry4HPyKK+k68Q3n6gih+aPO4k03eI1pDgiWfoZhnRFMslrQKZGQpbg1UXZJouQfE71E+OfEqM4dZ+Cob7aYTcMO8/ULZAve3WeIb0TIa3PeTPQPZBX0TBHCHWayR37aJoEk=,iv:x8689ejkki8VkLZ0N9mcJLI7Tk5uKs8bTzD318IQg3A=,tag:7x9v8iiH2T/kh7kw0dJUCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
