apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
type: Opaque
stringData:
    oauth-client-id: ENC[AES256_GCM,data:DACNMx17+HWIbx3JRpG7gPmI2VvKwFzQlYEQYrESDeZ9kbx9,iv:diioCo7HweshupTkE7lmOZ47lcJ9j7fdjhrLYdOhHzo=,tag:MeXDwbc6kF4QwhDe8lhozg==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:04KhGjSo5O763zD1meNHJx1OQNkYGhAwPAxIHCWz1Ko=,iv:aD9hXQkqO8rqKckdaaeOWCpiUcGn9Vp7Mk9VA7fmAqk=,tag:+ix072GE2sBVjJVYorKKqw==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY0ZILzJtUEtjcnNkSmdU
            Ukh6YVBVZjd4SG5IZFQwZUdEVVo0QUZCcENjClEyZHVZcnljL0FMUUpLV0JPNWVk
            eXJKdURhajVKT1YzNndhYnYzQWlFRlkKLS0tIEhhVG5WaWliWWVKbWpHQVRxSjNt
            b1JWUTlDMEU0cWU2K3MyVnZ3TEQyTlUKtaXD3r+AEwB/QYrrZWeRZ4d17CDR0Kmr
            TfqHrDCfIXKuzVA6DtOhQBszSEMdEFEmAhtPWHI4fQW7qNSlEwwRsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T05:42:22Z"
    mac: ENC[AES256_GCM,data:7+BZKngkpSWEwiUK2/A6ldxVRxyOmEInCTSTA7/43q6yyk2XjjjMbH2ZyzQunezvYyeP1MyQXR1qeMJnACo5ubNOsUzWWF0TjCL66GiQEOPF/FxO/H0KSyUQhx/3yy3avA0MLuMJKNg2bd/5VaSyiLGkgDRArJt2uIzWUMH2Z4o=,iv:ZEg4ynUGS7mTu9r5LrRZdePjl665Ec6qByiBsEFa1N0=,tag:17ji2fE27ObtTGUPNtU9wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
