apiVersion: v1
kind: Secret
metadata:
    name: kaneo-secret
    namespace: kaneo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:zg+HTCZHOfJim70RMJIXQiNmjUdpCpNFgvzXNZSjujhk2CWN9i6EnpsYZxs6CYm5kN0qu3miyxirH1xYVkQpHqyEgmsJN1rFEzdd8K73DvfJWTfn0ac/,iv:vKA8mrOgJpbG7aPdLLh6uEfY7iSv7pgCFayYN+XD72c=,tag:2LcdK14ZBv1OWEw0oaY3Sw==,type:comment]
    auth-secret: ENC[AES256_GCM,data:fHuBMUrIx0l60NYLCljQQM5AWI+X05L157Px+y8ysuKkFMBXl6+eidfiyr8JnjLOnPGV+kOfgbH7b4DUoVfztA==,iv:nKP5D4nzrbHy0aafd2LwINYGFd7VypeBc1EGHU2d9/o=,tag:5OTJcuVeJvjl0l3LQHTIKQ==,type:str]
    #ENC[AES256_GCM,data:7QVmtTSGg0nmmftz7yUrEAzYw4ArBmwbhDcIXxgICAcKw0nM72Z6VLBWvbe0+UUz/M79wmULnwRjAckp3Ykubt/0DAkK+u0oVwovHrKR,iv:g1OIHEXA5Zz80k7u/dssZH7ZZ+hMm/Cox1dJJImOrOQ=,tag:gEIkQpfjevUYlhTd5+lefQ==,type:comment]
    postgres-password: ENC[AES256_GCM,data:J42M2DS/01eg3iJEK6GVB9pgOjmrXR0ZYb9BEhbKV7o=,iv:2uW08vsnB0SOSmFWz++1Z2SNao/mQzG4WmT9Xu0l4B4=,tag:/1MnTCu8dvyolt5G10Ejbg==,type:str]
    #ENC[AES256_GCM,data:7rx1tQlPbo3lrNSdSMpKAlDXSpTtZrv6ugnU4CZIiBCoFnTwiBhASWr4Z46U0CrExU1G,iv:c/sH3hfQpGfvM+vlCn0IuzBRF4KwC1CevEO6ePQvQyI=,tag:1MGz8hbBmdjU1Ml8hE4O9w==,type:comment]
    #ENC[AES256_GCM,data:5Q2MVUvsBSv25f7QZ0OpHqlREoCqg2BaY6crbPqCwkcjMnJlSwJ/DxVwfJKl0CCDVb+xMhp6U1HPaCjXg91Q1hzOrB1uF5xzrEA5YCE=,iv:1mEdTCxifdiRRieYdrbgWbjBJNHEHKAImiHhS9G911Y=,tag:G9ULr0Yhven7cwrCPBgLQA==,type:comment]
    #ENC[AES256_GCM,data:NCyk2X/83QRuQrbb7cbXeQFNjiI0RrCqUpDjmGyU+WACmyyuXWrQG+khCSGlu61J0a9RMv3ZbiQ686nO4PFWDcEYae2Cw7lL,iv:V/AvHHuXy2uf2vy02NidEJP3QZuO1CY59WY/NrCP/zM=,tag:+s+X2IO0IXVLaN/g7pxQqg==,type:comment]
    #ENC[AES256_GCM,data:CmkRKpeiKrfEIhuNUOn3cBIqw3Z9qP2NwdYtsK9oZK6nlseC7S7A3rh91Oh+C8m6PL/3CTldkFI89JzBgJxSlMpgv4u7svK57tlv4lIc,iv:LmPdU9jx1RwbLAxlWSKAFPfD+7lHqRvCMCEhIuD0sd4=,tag:7vKdpWcmS2vTLEziI4EjUQ==,type:comment]
    #ENC[AES256_GCM,data:kyY99zw8D9nZV82ksgSYBh6fwZbW5Hmo9Vk7KMT0BmUAr0OyGlosovU7LsT9ibJhtAqt,iv:x7FDxbVO1uYQNVU7j4NzGllFyTIeXNSBoCzDlhlveCo=,tag:xf6MKNSYbua342VE146LdQ==,type:comment]
    database-url: ENC[AES256_GCM,data:aRsKagFRVasbGBsrS9LJ63lq5zAOYqwi1DL4u/sPFK1TtOIPU3IX6cJzXyK1u/f4vgOq9UjoaeD1N4DweufQcCl6Nu+ZSuUgEyJn9KFrk0zNfloo,iv:7ahDU/cD49yk5TnTys5208Iv2OAGwMUTiSiIBYtkooo=,tag:MkmN7K2GAjat7Ja4Lh/Vzw==,type:str]
    #ENC[AES256_GCM,data:MZgJ9KZ2N4/IpeklILOqyZh1a4ek1PSFHKSmbrFKw86FLwt4f15W+FhJG9FE3zB2GxeObrTkHh6l0RsEOMY5a24E,iv:LabRl4P11xBs43Z66wIoGr53K1g5T3fYk+MjNHn2yks=,tag:UklU3SC1TQfmyKXVM5IMxQ==,type:comment]
    #ENC[AES256_GCM,data:B6NS+d44/+2hcqyDkD4X3sFokIuGd46hIXzQR9vRXVQubrz6DLO41f/7L2cOGXVYtnchqG1mnk83/EjyGWrxaWs=,iv:Ez4A5srdkYmisn17ao0zZSJ6GeqHH6I9FCNNKXP7iXU=,tag:QjJht0sDHEaGlCYR/740Rg==,type:comment]
    #ENC[AES256_GCM,data:PQKZe9Ah3WVcemjF/LX3ToM+HvcGfQY+c6wbe6tm4LAYj2CzDUFgFTR0lDuDAq7jOLzkw2EK/UinWDtLXRI=,iv:dSmn0sYxonsW91+Tu0q02JRHkhCFWHCOk2J1TL1xpBs=,tag:5chRt8+pZAVMeNswc6CY+w==,type:comment]
    #ENC[AES256_GCM,data:CJP/RuvskxAh5B62JLoSC9ozF7rGarskMMcCRwgDTc1kFI7wgpfcnN9Y0vf72PS5DV6QQIQJXeKa9h949EV0UsPFCB+jYFx7CWoZNwHBTi1GcAM=,iv:TDKhkvyxAitLR1uqKvwUlkU+g7XGNd6J8Rxe2iSMxWM=,tag:JkxRZLowrHOFV0pY0Uzdxg==,type:comment]
    #ENC[AES256_GCM,data:aT6cJrfW4AfNfqQHJgBdA9rhq3cNKTMvYe/ERrFcSKIO,iv:Q7dtD0Yy9dpkjVZZfC3A5alDtoeAerMjegMHzfpz4PQ=,tag:AAa5ndnpsFYwPD+pbLj3MQ==,type:comment]
    oauth-client-id: ENC[AES256_GCM,data:puHUB61s6IBolctLf2a5gqleG4lzmY14CLKPrIhRUKaCkpda,iv:FTMBpZKwm1I6dnz4OPdYFfw9i+ZmZkiNwm6frzLQr84=,tag:wpp2GEQU+T/sxZpdLhnrDA==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:I7UCJgzf1BDdX2JPIRLMVZbZBhY5YwhsWHNeqv0W29A=,iv:aqBV2jJvQr7JSye0nIr46MuLXrfD0XoUt5+9UHmAiEQ=,tag:nfWLX4Gm+tZ2Af2M0/X5Mg==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSTRFajlVT3RsQzdDOWpF
            ZTc4T2JvVTJNU1VlK3dKSkNkNmV2T0xXMFQwCmtOWHAwdU9EWURLTGJ3d29zRFE5
            Uk41TktKdGNIck0vTlZaVk5pSFREQkUKLS0tIGxpUHFHKzlGLzdVbFFpZVpDVEtG
            QzhLRE9oOW9HbWcrUzJCVlROVDk4TEUKUr9rRFw+QxQcUzlsKIrosH6BMcS7HLTh
            k+9CRfkPE63fcezpxZEg1zBNCBqHkin5Ca8bstY8vKQeyfD4PFKeqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T03:58:40Z"
    mac: ENC[AES256_GCM,data:cJF0sl27bJH/jYJ10L8tVKjSeHyDtKp7lGJZWtYS1NTBs/LrlesB85KrKbIWO1sbZ1ifRxBtsaHVi1TcmfihOcyr94p4k5iNUWdv7/uH6Wrnrf+Bv2VbhxDzteb/aE5KfADXkazt1l2bNvqjLiJD9bV3Ru4Ir1CsBiQLy5/sq6M=,iv:VZ8QW2ZDS+1xAR6ArCoZHGRQ/o8fngycODm9ZMaV4bM=,tag:PT5DUqZtjqiTdGVWllVwoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
