vault_alloy_basic_auth_username: ENC[AES256_GCM,data:nGriDhA=,iv:gm+tUyXKIADITuQOLZu8mmbve3so2/jGmhgnuV3lROQ=,tag:Oj0bAaS1136S9EiG1QnmjQ==,type:str]
vault_alloy_basic_auth_password: ENC[AES256_GCM,data:4eb5BJ5HIF1MQttg7ZRC+jxBW8mKxexk65yl23n0hEMbrpkpmeNH4NZGqw==,iv:XuTsBntX+Rw4CdtX9niLPvaz2RIXKf+lEU8UyK/s62w=,tag:4uXhnousXKV2P2GWBbqEPw==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQUR1a0w2UmVVdjhwRFlJ
            ZlNIZmNjTGhtK3NlQ0duSTBzemxnd1FKdG1JClQ1UDQ0N3VEbFNQeVNkaVJqekNl
            VjBsand4K0ZGZldub3M5RzVkZWpRZGcKLS0tIHcrL1dpL3V0VzVBRTlpMkJyNEVU
            OW5jT1lBUUJyY1VLeW9LYlB5T09YQzAKJbmq9Es0oLw+kt4F6ZWa0Vaj0d4UCvmP
            4G3P9YTqzmQL4DP+6KuJBnyKYwcuzQiKjqWhsFyasX/ktDMNSOg/mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:57:23Z"
    mac: ENC[AES256_GCM,data:pyUHQ/t0FM1nCFIhSem6eC5JabZJDHYGW4uiSU9xcDScNABeq4xtu3X09XPVxwKwsH4QU9NZFzkMZBOtcA+dF9i4fgvmcsoVTO7PQKxCXMDX44Hni5cGNxgLBClNhwIhbxqZUgBp2pEmQKiN/HgJ3FzxAhQUDkENQ4W72K1uKqw=,iv:f3ul3tXypa6PyKx4WGs0H1gFUHkTtmflfw+erBS8KXU=,tag:cH1HqPDSGJQCCVvhN6UGWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
