vault_alloy_basic_auth_username: ENC[AES256_GCM,data:NCyRj0Y=,iv:qbKlQll/ISQZ4TqkLD0oSPW9UW7v+NPERxaLRU0vpNc=,tag:TVnwmWWVHlyGdJPjfP6CJg==,type:str]
vault_alloy_basic_auth_password: ENC[AES256_GCM,data:EjpTW6oxF40tWu3yJn5V/85mem38h0mdlIgMAhn7nQDJJlyPQ18qnahL3Q==,iv:qPLmyTnELk80uNFAAxm+rj+KhhtSGA0TKmshXIy9J08=,tag:YOTNr6Aert9j2p1/ZO3IkA==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S3F3NmVpZnJBN3lOVm5y
            ckRoaVFmYjNSWTd6a2VJUVg3MHRCc0NTUzEwCmFqdUdiZ3ZoN2pFSUMyYXVSVEhK
            a2ozWXZVeStIMldBaXphUWVYc0IxamMKLS0tIEpBMHBXSlpSMjNIclBETUxid2to
            Ykt4T09qNmRnenhPNDhlZ0ptOE9UTHcKeGnhaxmH4o2vSUD7nCwfyyrVkq4OjryC
            ddP7leWkZwgySpszoBKXxpXI6K4k2Y6muSd4bltBuu1jswZMNsBOAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T04:59:21Z"
    mac: ENC[AES256_GCM,data:ZcPBwrycM4U8tfwC81oYcdwvbLXiIOOfrjXjj6fYD3KQXq58HUP65cc0ZbBxjAnpCbM3jy1S7Hk3avPXLZyfCjx802ivovnDroOkhNysZfBeLMb7J448g0pF39C4jZltlOKhIlfyOGPCBeRakkknQL8V9mo+pG9fMEHfrqUN5uU=,iv:Svom6thVSg8KJCkm3tkqov4LQ3QpisCFyONHfAuDGLA=,tag:MsC4UAKnr3nr6sgAxBDRfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
