vault_alloy_basic_auth_username: ENC[AES256_GCM,data:nGriDhA=,iv:gm+tUyXKIADITuQOLZu8mmbve3so2/jGmhgnuV3lROQ=,tag:Oj0bAaS1136S9EiG1QnmjQ==,type:str]
vault_alloy_basic_auth_password: ENC[AES256_GCM,data:4eb5BJ5HIF1MQttg7ZRC+jxBW8mKxexk65yl23n0hEMbrpkpmeNH4NZGqw==,iv:XuTsBntX+Rw4CdtX9niLPvaz2RIXKf+lEU8UyK/s62w=,tag:4uXhnousXKV2P2GWBbqEPw==,type:str]
vault_rd_api_key: ENC[AES256_GCM,data:UOZsJhrIasT5CMbF+CO8E0zmwnsnDrA6mOXtEVEumbXBUUrCdFb1XNUJZuwd6jfnkUrbHg==,iv:6ePrjNuV7bdY7R4Kw232pN7iep3CqMxTWMb6erpovtA=,tag:RjWy5pj6afs2qOTwzpF8zg==,type:str]
vault_opensub_username: ENC[AES256_GCM,data:8t41+VrcQ98P/w5/Fg==,iv:sjac78uFIrZ2Z8urFcGCuPrS5wTPxTVtfjfAhKAGAp8=,tag:wbqQuT3FSN0rTD/bJSef+A==,type:str]
vault_opensub_password: ENC[AES256_GCM,data:AVSoeAkVFRIz+xt1US4Gzw==,iv:G3r79LemZj+vBA1Sm12uFuTjSzaMfGwG9CiN6mo3VQU=,tag:/C72fZw4V6LVDBzpxgC4+A==,type:str]
vault_pve03_api_password: ENC[AES256_GCM,data:IVj5eaMGC4Brk0aZjXfx,iv:fpdryzrJvTToyKm0GWAmQ5ARbD2TtteZNzPVv+dANNk=,tag:PxZCDe5ejU3HiplqChVKxQ==,type:str]
vault_jellyfin_api_key: ENC[AES256_GCM,data:PbIVhxEuD0hhoK3QUxjv7OdhGk6ZBz6+wTh9/yNxqjo=,iv:eIb2QvqnWuF6mDHgJ/6WacUAXh25wN/2VsP7Kh89qHc=,tag:0mo44SQ2aDORAIKfI2P1cQ==,type:str]
vault_radarr_api_key: ENC[AES256_GCM,data:tjeBb92Ql79rlZAd0z2pul27YpPDI1DdI15Z0qrvE3s=,iv:ZwgBRz7FdSIKhNWCrZTTqPrnnQ+QrZ+i8iwPIkfrVGI=,tag:j8S/lL2kwoa3VzbCzCAvTg==,type:str]
vault_sonarr_api_key: ENC[AES256_GCM,data:a0jOkPMaQkCarG0oZo/EtN36ht/EVnyiX5YUkPsnvM8=,iv:0OcrZTkuTKX3DaBDyVEzxMPNWmjKCmPBsouhwON4ALA=,tag:LfLnuQTzA+65W4jtZlLFEw==,type:str]
vault_prowlarr_api_key: ENC[AES256_GCM,data:wbnzZIJKJiEXRO4NYnYIErJKOwcOUz9lW0bR944jcP0=,iv:bUDyiZWQTusl8x9u1eFZgi8j0Yox12Zy4yrFjOvAvQg=,tag:Y8re51v8iAnZ3el4ivz0yg==,type:str]
vault_bazarr_api_key: ENC[AES256_GCM,data:X3WtsGVZFIEpv2TfGFH+QSwVExNwPg80exV+Ddzcr5I=,iv:jFsPSAiSPF3YCk9gUYl4k3dNdHRQDj9VQ0dLbqbqghM=,tag:8Q9AOnEUMVKSXIimWbRlbA==,type:str]
vault_jellystat_db_password: ENC[AES256_GCM,data:dKXkor+imjiQPlmNgvylqUTTzwhSXqf76U5f/Mgoypg=,iv:0havMUDFPkOVdTD5r34/zvDJU24G7wxnqpBmRdLhRUM=,tag:AqJYH5ucYWbuc/JSMqTX3Q==,type:str]
vault_jellystat_jwt_secret: ENC[AES256_GCM,data:+kT26TBY/kV2gaNdK83BITUcLmAaL2d/eeYiwKYwVZCI6FrsK7JJwJV/X9qiSismWBXgGNZ5Lk4EMNVsuCebJg==,iv:rdyOGZfyGNPh5EgThayAstm/tf+i1UhtftuWied8fOM=,tag:EElD40eri53ucQqAgkUlxQ==,type:str]
sops:
    age:
        - recipient: age1y6dnshya496nf3072zudw3vd33723v02g3tfvpt563zng0xd9ghqwzj5xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQUR1a0w2UmVVdjhwRFlJ
            ZlNIZmNjTGhtK3NlQ0duSTBzemxnd1FKdG1JClQ1UDQ0N3VEbFNQeVNkaVJqekNl
            VjBsand4K0ZGZldub3M5RzVkZWpRZGcKLS0tIHcrL1dpL3V0VzVBRTlpMkJyNEVU
            OW5jT1lBUUJyY1VLeW9LYlB5T09YQzAKJbmq9Es0oLw+kt4F6ZWa0Vaj0d4UCvmP
            4G3P9YTqzmQL4DP+6KuJBnyKYwcuzQiKjqWhsFyasX/ktDMNSOg/mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T22:11:45Z"
    mac: ENC[AES256_GCM,data:MCfbrGxZ6jhT0N3rSqfUUEo5K79BzP2mTk43sdRT8zdaGKhR7JXM4MBRsjeWA9EbG7dlcvHcuFmaGPZ4o2OVog3bChgj4pEgaKdnqm4Ec7Ef4oYR8bp+I6inApiXXSOJc/KHQ6+FcBSuk+BCQogEg7wkS2aFZPJFjEcgYcTBoxg=,iv:fdBK2fQvwkbnFHIMSKkO/I95RcnnUDRZeEFco/4Nv64=,tag:h6C7h5+Pchwkoz6I9PCaWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
