services:
  pangolin-cli:
    image: fosrl/cli:0.16.0
    container_name: pangolin-client-obs
    restart: unless-stopped
    network_mode: host
    command: ["--upstream-dns=1.1.1.1", "--netstack-dns=1.1.1.1"]
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
